version: '3.8'

services:
  # PostgreSQL Database for Accounts Service
  accounts-db:
    image: postgres:15
    container_name: accounts-postgres
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: accounts_user
      POSTGRES_PASSWORD: accounts_password
    ports:
      - "5432:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data
      - ./init-databases:/docker-entrypoint-initdb.d
    networks:
      - bank-network

  # PostgreSQL Database for Cards Service
  cards-db:
    image: postgres:15
    container_name: cards-postgres
    environment:
      POSTGRES_DB: cards_db
      POSTGRES_USER: cards_user
      POSTGRES_PASSWORD: cards_password
    ports:
      - "5433:5432"
    volumes:
      - cards_data:/var/lib/postgresql/data
      - ./init-databases:/docker-entrypoint-initdb.d
    networks:
      - bank-network

  # PostgreSQL Database for Loans Service
  loans-db:
    image: postgres:15
    container_name: loans-postgres
    environment:
      POSTGRES_DB: loans_db
      POSTGRES_USER: loans_user
      POSTGRES_PASSWORD: loans_password
    ports:
      - "5434:5432"
    volumes:
      - loans_data:/var/lib/postgresql/data
      - ./init-databases:/docker-entrypoint-initdb.d
    networks:
      - bank-network

volumes:
  accounts_data:
  cards_data:
  loans_data:

# Define custom network
networks:
  bank-network:
    driver: bridge