version: '3.8'

services:
  # PostgreSQL Database for Accounts Service
  accounts-db:
    image: postgres:15
    container_name: accounts-postgres
    environment:
      POSTGRES_DB: accounts_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data
      - ./account-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accounts_user -d accounts_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL Database for Cards Service
  cards-db:
    image: postgres:15
    container_name: cards-postgres
    environment:
      POSTGRES_DB: card_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - cards_data:/var/lib/postgresql/data
      - ./card-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cards_user -d cards_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL Database for Loans Service
  loans-db:
    image: postgres:15
    container_name: loans-postgres
    environment:
      POSTGRES_DB: loan_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - loans_data:/var/lib/postgresql/data
      - ./loan-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loan_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL Database for User Service
  user-db:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./user-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL Database for Transaction Service
  transactions-db:
    image: postgres:15
    container_name: transactions-postgres
    environment:
      POSTGRES_DB: transactions_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - transactions_data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transactions_user -d transactions_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL Database for Analytics Service
  analytics-db:
    image: postgres:15
    container_name: analytics-postgres
    environment:
      POSTGRES_DB: analytics_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    volumes:
      - analytics_data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analytics_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  accounts_data:
  cards_data:
  loans_data:
  user_data:
  transactions_data:
  analytics_data:

networks:
  bank-network:
    driver: bridge
