server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Routes
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - name: JwtAuthenticationFilter
        
        # Card Service Routes
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/cards/**
          filters:
            - StripPrefix=0
            - name: JwtAuthenticationFilter
        
        # Accounts Service Routes
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=0
            - name: JwtAuthenticationFilter
        
        # Loans Service Routes
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=0
            - name: JwtAuthenticationFilter

jwt:
  secret: ${JWT_SECRET:e9fa4786dadbdf5913ca849bc146e242f7fe646694b40ea3c88163461468ef31}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.api_gateway: DEBUG