server:
  port: 8081

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5435/user_service_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    
jwt:
  secret: e9fa4786dadbdf5913ca849bc146e242f7fe646694b40ea3c88163461468ef31
  expiration: 86400000 # 24 hours in milliseconds
  
logging:
  level:
    com.example.user_service: DEBUG
    org.springframework.security: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true