server:
  port: 8082

spring:
  application:
    name: card-service


  datasource:
    url: jdbc:postgresql://localhost:5433/cards_db
    username: cards_user
    password: cards_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
