server:
  port: 8082

spring:
  application:
    name: card-service


  datasource:
#    url: jdbc:postgresql://localhost:5433/cards_db
#    username: cards_user
#    password: cards_password
    url: jdbc:postgresql://localhost:5436/card_service_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:e9fa4786dadbdf5913ca849bc146e242f7fe646694b40ea3c88163461468ef31}
  expiration: ${JWT_EXPIRATION:86400000}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

logging:
  level:
    com.example.card_service: DEBUG
